[package]
name = "webrender_playground"
version = "0.1.0"
authors = ["Tristan Hume <tristan@thume.ca>"]

[dependencies]
webrender = { path = "../webrender/webrender" }
# servo-glutin = "0.11"     # for the example apps
gleam = "0.4.8"
glutin = "0.9.2"
